### ISSUE TITLE
Dependencies, secret.json

### ISSUE THREAD

**Issue by mikado98765** [nzsilverman/climbing_carpools#4]
Are the dependencies included in the package? If not, you might want to mention in the README some of the dependencies that are necessary (oauth2client and gspread were the ones that I had to install). Also, running `python3 schedluer` gives me the following error
```Traceback (most recent call last):

  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)

  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)

  File "scheduler/__main__.py", line 54, in <module>
    main()

  File "scheduler/__main__.py", line 13, in main
    form_responses = create_lists(sheet_name, dues_sheet_name)

  File "scheduler/read_responses.py", line 56, in create_lists
    responses = get_responses_from_spreadsheet(sheet_name, dues_sheet_name)

  File "scheduler/read_responses.py", line 21, in get_responses_from_spreadsheet
    json_key = json.load(open(SECRETS_FILE))

FileNotFoundError: [Errno 2] No such file or directory: 'secret.json'
```
Not sure if its something wrong on my system

**Comment by cwentland0** [comment]
Dependencies are not included, but it's easy enough to add them to `setup.py` so that `pip` will automatically install them during setup.

**Comment by nzsilverman** [comment]
The dependencies should be in the setup.py file. I probably forgot to include those two dependencies in that file. I can fix that later, thanks for finding that. As far as the error goes, you need a secret.json file which is the key to let you access the google developer api. If you post (or email me) your umich email I can add you to the developer console and you can download a key

**Comment by mikado98765** [comment]
Whoops didn't read the README very well that's my bad. Umich email is mohtake@umich.edu

**Comment by nzsilverman** [comment]
Added you, you should be able to get on now.

**Comment by nzsilverman** [comment]
Let me know if you have problems
