### ISSUE TITLE
Investigate/ Fix Am/ PM bug

### ISSUE THREAD

**Issue by nzsilverman** [nzsilverman/climbing_carpools#40]
The times inputted do not (or maybe they do) have am/pm associated with them. Make it so the code can handle am/pm conversions and time matching. This will involve investigating the google form

**Comment by rkalnins** [comment]
- [x] Add AM/PM to drop down and check box options in the Google Form
- [x] Update time parsing to remove AM/PM and convert to 24-hr time
- [x] When writing to sheet, go to 12-hr time with AM/PM
