### ISSUE TITLE
Improve Efficiency and Refactor Some Code

### ISSUE THREAD

**Issue by jonahrosenblum** [nzsilverman/climbing_carpools#7]
## read_responses.py: 
**line 44** - replace the list with a set, improve lookup time from O(n) to O(1)

## generate_rides.py: 
**line 8**  - this can be a one liner.
def get_total_seats(drivers):
    """ Returns the number of available seats for passengers. """
    return sum([driver.num_riders for driver in drivers])

**line 32** - combine the two if statements, it will be faster in the case that the first one isn't true, but it will also be easier to follow.

**line 54** - typo, "this" is spelled wrong.

**line 78** - replace the num_riders counter with len(riders), it's still constant time, and move the shuffling of the riders to outside the while loop, it's just as random to shuffle it once and it's slower to do it every iteration.
 
If I find more I'll add them.

**Comment by jonahrosenblum** [comment]
If someone could assign these to me I'd appreciate it, I'll do this after dinner.

**Comment by nzsilverman** [comment]
These sound like good improvements. I will add you as a collaborator on this project so that you can make a branch and then make a pull request to push them back into master once they are good. Thanks for catching those things.
